### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by chlinp** [chlinp/blog#13]
## 安装
> https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

### Ubuntu 16.04
```bash
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

sudo apt-get update

sudo apt-get install -y mongodb-org

# 安装好后修改配置文件，注意新建好db文件夹，如/data/db/
vim /etc/mongod.conf
```

#### 创建mongodb用户组和用户
```bash
$ groupadd mongodb 
$ useradd -r -g mongodb -s /sbin/nologin -M mongodb
```

#### 官网下载
https://www.mongodb.com/download-center?jmp=nav#community

#### 下载好，解压缩
> tar -xvf mongodb-linux-x86_64-ubuntu1604-4.0.2.tgz

#### 创建mongodb文件夹
```bash
mkdir -p /usr/local/mongodb/data        # 数据库存放目录
mkdir -p /usr/local/mongodb/conf       # 数据库配置文件存放目录
mkdir -p /var/run/mongodb                # 数据库pid存放目录
mkdir -p /var/log/mongodb               # 数据库日志存放目录
```

#### 移动到/usr/local/mongodb/
> mv mongodb-linux-x86_64-ubuntu1604-4.0.2 /usr/local/mongodb

#### 创建/usr/local/mongodb/conf/mongodb.conf
```bash
bind_ip=0.0.0.0                          #指定此mongodb的ip，用于外网通信，本地的话可以设置为127.0.0.1，或者注释掉
port = 27017                                  #端口
logpath = /var/log/mongodb/mongodb.log        #日志文件路径
dbpath = /usr/local/mongodb/data              #数据库文件路径
pidfilepath = /var/run/mongodb/mongodb.pid    #pid文件路径
maxConns = 65535          #优化连接数
slowms=200                #记录profile分析的慢查询的时间，默认是100毫秒
fork = true               #以守护进程运行
logappend = true          #日志追加模式，否则，重启mongo，日志会被覆盖
directoryperdb=true       #设置为true，修改数据目录存储模式，MongoDB将数据存储在不同的磁盘设备#上，以提高写入吞吐量或磁盘容量
                          #注意：要是在运行一段时间的数据库中，开启该参数，会导致原始的数据都会消失（注释参数则会回来）。
auth=true # 开启认证
```

`YAML`方式:
```
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile

security:  
    authorization: enabled # disabled

setParameter:
    connPoolMaxShardedConnsPerHost: 200
    connPoolMaxConnsPerHost: 200
    notablescan: 0

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```

#### 修改mongodb目录权限
```bash
chown -R mongodb:mongodb /usr/local/mongodb
chown -R mongodb:mongodb /var/run/mongodb
chown -R mongodb:mongodb /var/log/mongodb
```

#### 将mongodb命令加入环境变量，修改profile文件
```bash
$ vim /etc/profile , 添加到最后面
export PATH=$PATH:/usr/local/mongodb/bin/
$ source /etc/profile
```

#### 添加启动脚本
```bash
# 新建文件，赋权
$ touch start.sh
$ chmod 755 start.sh
$vim start.sh

#!/bin/sh
### BEGIN INIT INFO
# Provides: mongod
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop:     
# Short-Description: mongodb service
### END INIT INFO

MONGOD=/usr/local/mongodb/bin/mongod
CONFIG=/usr/local/mongodb/conf/mongodb.conf

start_mongodb() 
{
    ps -ef | grep -v "grep" | grep "$MONGOD"
    if [ $? -eq 0 ];then
        echo "mongodb is in running!"
        return 0
    fi
        $MONGOD --config $CONFIG &
}

stop_mongodb()
{
    $MONGOD --config $CONFIG --shutdown
    if [ $? -eq 0 ];then
        echo "stop mongodb service successfully!"
    else
        echo "stop mongodb service failed!"
    fi
}

query_status()
{
    ps -ef | grep -v "grep" | grep "$MONGOD"
    if [ $? -eq 0 ];then
        echo "mongodb is in running!"
    else
        echo "mongodb is not in running!"
    fi
}

case "$1" in
    start)
        start_mongodb
        ;;
    stop)
        stop_mongodb
        ;;
    restart)
        stop_mongodb
        start_mongodb
        ;;
    status)
        query_status
        ;;
    *)
        echo "温馨提示使用方法: sh start.sh start|stop|restart|status，不涉及kill等强制命令，请放心使用"
        ;;
esac

exit 0
```
源码安装参考链接： https://my.oschina.net/zhouyuntai/blog/1826182

### 命令

启动
> sudo service mongod start

停止
> sudo service mongod stop

重启
> sudo service mongod restart

使用
> mongo --host 127.0.0.1:27017

#### 创建用户
```bash
use admin
db.createUser(
  {
    user: "myUserAdmin",
    pwd: "abc123",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)

db.createUser(
  {
    user: "admin",
    pwd: "12345",
    roles: [ { role: "readWrite", db: "libtorrent" } ],
    mechanisms : ["SCRAM-SHA-1"] 
  }
)
```
